### PR TITLE
Proposal for new chapter on "Introduction to Quantum Mechanics"

### PR DESCRIPTION
**Pull request by AbeerVaishnav13**
# Introduction to Quantum Mechanics
**Folder:** ch-intro-to-qm
**Chapter Title:** Introduction to Quantum Mechanics
**Initial contributors:** @AbeerVaishnav13, @rupeshknn , @na13neil

## What should readers gain from this new content?
This is a proposal for a potential new chapter which aims to guide beginners in the field of quantum computing and provide them with information regarding the chronological evolution of the field as well the mathematics/physics formalisms and constructs that are necessary to develop a deep understanding of the subject.

The first section here talks about the historical background of quantum mechanics and will give a deeper understanding as to how the idea grew starting from Planck's hypothesis to the famous Stern-Gerlach experiment. The further sections in the chapter, as mentioned in the content table below, show a transition from Classical Mechanics to Quantum Mechanics. This approach helps in bridging the knowledge gap that is currently present in the textbook and also helps one to visualize how quantum mechanics is different (or similar) from classical physics. The chapter focuses on tackling the problem of understanding the much-needed topics discussed in the further chapters of the textbook. This includes chapters related to various quantum operations and even quantum hardware. The aim of this chapter is to give useful content for the readers and provide them with a good foundation for their future learnings.

Potential list of topics (each section below will be a single jupyter notebook, section titles not confirmed):
1. History of Quantum Physics
    - Planck
    - Photoelectric effect
    - Bohr
    - Stern-Gerlach
2. Classical formalisms
    - Lagrangian
    - Hamiltonian
    - Poisson's bracket
    - Canonical quantization
3. Quantum formalisms
    - From classical to quantum
    - Hilbert space
    - Dirac notation
    - Operators in QM
    - Commutators
4. Time-evolution of quantum systems
    - Schrodinger's picture
    - Heisenberg's picture
    - Dirac's picture
5. Second-quantization
    - SHM in QM
    - Annihilation and Creation Operators
    - 2nd Quantization of a Hamiltonian

## Where do you expect this new content to fit in with the current content?
We would like to add a new chapter into the Qiskit Textbook with the title, "Introduction to Quantum Mechanics". The chapter can be placed as an introduction chapter (along with current chapter 1 and 2) or before the point where one starts with the quantum hardware concepts (chapter 5 and 6), as it will aim towards introducing intuitions regarding the mathematics and physics required to tackle the quantum mechanics discussed further in the textbook.

## What material should this new content be based on?
It would be a condensed version and combination of various famous books/texts for Quantum Mechanics. The inspiration would be from the book by Susskind[6], which explains complex concepts in a simple way. We will also try to include the related mathematical concepts for explaining the advanced contents in the later sections (section 4 and 5).

## Are you proposing to write this new content? (y/n)
Yes, we are planning to write this chapter as a new addition to the qiskit textbook. However, we welcome researchers and other subject experts also if they want to contribute to it.

## References
[1] Three Approaches to the Quantum‚ÄîClassical Relation: Bohr, Heisenberg, and Dirac Author(s): Alisa Bokulich;http://www.jstor.org/stable/23354109
[2] Development of the analogy between classical and quantum mechanics, N MUKUNDA.
[3] On The Analog Between Classical and Quantum Mechanics, PAM Dirac.
[4] Dirac‚Äôs Classical-Quantum Analogy for the Harmonic Oscillator: Classical Aspects in Thermal Radiation Including Zero-Point Radiation, Timothy H. Boyer
[5] Open or Closed? Dirac, Heisenberg, and the Relation between Classical and Quantum Mechanics, Alisa Bokulich
[6] Quantum Mechanics:: The Theoretical Minimum, Leonard Susskind
[7] Feynman, R. Leighton, and M. Sands, (Addison-Wesley, Boston, 1963), Vol. 3, WWW Document, (https://www.feynmanlectures.caltech.edu/III_toc.html).
[8] Griffiths, David J. Introduction to Quantum Mechanics. Upper Saddle River, NJ: Pearson Prentice Hall, 2005. Print.

### CODE REVIEW

**Comment by frankharkins** [comment]
This is a really nice idea, but I think it's out of the scope of the Qiskit textbook. I think the textbook needs to focus on quantum computing, which is already a large subject, and teaching quantum physics should be left to external resources. This proposal would add 19 notebooks, roughly ~30% of the current textbook, and I don't think we have the resources to maintain that. If the goal is to prepare readers for chapter 6, we could include a page with recommended external resources?

I'm open to other opinions on this.

**Comment by AbeerVaishnav13** [comment]
Hi @frankharkins , thanks for your reply.
I'm sorry for the confusion, but by saying that each section will have its own Jupyter notebook, we meant the sections numbered 1,2,3,4,5. So, in total, there will only be 5 notebooks in this chapter. I apologize for the miscommunication.

I understand your concern that these topics are not directly related to quantum computing, but for a beginner reading the qiskit textbook, it becomes really tedious to navigate through it if they aren't aware of something in advance. For example, in the section where the notebook discusses Transmon Physics, there's not much information on how the transmon hamiltonian is derived. The textbook only gives the final equation. Moreover, this textbook serves as an educational resource for people from multiple backgrounds who might not have in-depth knowledge of the underlying physics but still want to venture into quantum computing.

Hence, we all felt the need that for the sake of completion, a chapter on basic QM might be necessary for the reader to at least be able to have a glimpse of the required concepts to implement something in Qiskit code.

We put in this PR as we came across an old PR ( #17 ) which was never got merged and was left in between by the author. Hence, we thought of taking it up. Please let us know what you think about it.

**Comment by HwajungKang** [comment]
I agree what @frankharkins posted above, adding external resources needed to help the readers who wants to understand pulse level quantum computing as the amount material would not be trivial.

**Comment by frankharkins** [comment]
@AbeerVaishnav13 From your comment, I think the main problem you're trying to solve is (?):
>... for a beginner reading the qiskit textbook, it becomes really tedious to navigate through it if they aren't aware of something in advance.

And I think adding more 'warnings' about what is and isn't already covered, and linking to external resources would be the best short-term solution to this.

**Comment by AbeerVaishnav13** [comment]
Okay sure @HwajungKang and @frankharkins . We'll start looking into the prerequisites chapter as suggested by you and come up with an updated draft for the list of topics and resources in a few days. Thanks a lot for your time and for reviewing our proposal!

**Comment by frankharkins** [comment]
I'm going to close this, please open a new PR with the updated draft when it's ready

**Pull request closed without merging**
