### PR TITLE
Fix typos and a number in several sections

### PR DESCRIPTION
**Pull request by t-imamichi**
# Changes made

Fix typos and wrong person's name.

Fix the approximation ratio of Goemans and Williamson. It is described as 0.868 in the textbook. But the reality is 0.878.

# Justification

image

### CODE REVIEW

**Comment by veenaiyuri** [comment]
@frankharkins This PR has been sitting here for a while. Can you please verify and merge? It is a straight forward fix for typos and a specific value referenced in several places.

**Review by frankharkins — APPROVED** [review]
Thank you!

**Comment by veenaiyuri** [comment]
Thank you @frankharkins !

**Comment by t-imamichi** [comment]
Thank you for your cooperation!

**Pull request merged**
