### PR TITLE
Fix issue #1245

### PR DESCRIPTION
**Pull request by rafal-pracht**
# Changes made
I replace the "result = job.result().get_counts(self._circuit)" by "result = job.result().get_counts()" in definition of QuantumCircuit.

# Justification
Regarding to issue #1245 the new version is incompatible with experiments in textbook.

### CODE REVIEW

**Comment by rafal-pracht** [comment]
This fix is for the issue https://github.com/Qiskit/qiskit-aer/issues/1245

**Comment by jwoehr** [comment]
@rafal-pracht you are correct about the fix:
Change the line
```
result = job.result().get_counts(self._circuit)
```
to
```
 result = job.result().get_counts()
 ```
but you also changed other things in the notebook, e.g., number of counts, etc.

You should recreate your submission without the other changes.

I have tested the fix and [offered it on Qiskit Slack](https://qiskit.slack.com/archives/CB6C24TPB/p1620902501424100?thread_ts=1620862526.422600&cid=CB6C24TPB) to the latest user stung by #1038

**Comment by jwoehr** [comment]
I would suggest:

- Fork again the textbook repo (or create a fresh branch)
- Load the page in Jupyter Notebook
- Make the one code change
- Choose Reset Kernel & Run All from the menu
- Save and exit
- Submit a PR off of your new branch

**Comment by jwoehr** [comment]
#1085 replaces, you should simply close this PR, @rafal-pracht

**Comment by rafal-pracht** [comment]
@jwoehr  I've just done as you said, but this doesn't help. https://github.com/qiskit-community/qiskit-textbook/pull/1085

I think the issue is in the "make book" command, but I'm not sure.

**Comment by jwoehr** [comment]
What doesn't work, @rafal-pracht ? I'm not sure that I understand.

**Comment by rafal-pracht** [comment]
I close this PR, the new one is https://github.com/qiskit-community/qiskit-textbook/pull/1085

**Pull request closed without merging**
