### PR TITLE
Quantum Edge Detection chapter

### PR DESCRIPTION
**Pull request by AbeerVaishnav13**
# Changes made
This PR adds one chapter to the Qiskit Textbook, under the section 4.2.3 of the textbook.

# Justification
Qiskit textbook has had a chapter on **Quantum Image Processing - FRQI and NEQR Image Representations** (section 4.2.2) for a few months now. However, there are no resources on how to use these representations for any useful applications. This was my motivation to contribute to the textbook.

I have been working on this project for few weeks and have successfully implemented the Quantum Hadamard Edge Detection (QHED) algorithm in Qiskit and have tested this on actual image data (that has been provided in the notebook as well). This chapter contains a detailed explanation of the QHED algorithm and also presents implementation using Qiskit for images up to 256x256 in size.

Dear reviewers, I welcome any suggestions to make this chapter better in terms of information related to the application and also if there are any UX changes required for displaying it properly on the Qiskit textbook page.

Looking forward to this PR getting merged in the official repo. Thanks!

### CODE REVIEW

**Comment by frankharkins** [comment]
Hi @AbeerVaishnav13, thanks for your contribution! I will take a look ASAP

**Comment by AbeerVaishnav13** [comment]
Thanks a lot, @robertloredo for reviewing and appreciating my work here.
Yes definitely. I'll try to run it on mock backends then rather than actual hardware because the examples that I've chosen, actually require more than 5-qubits and the only free backend with >5-qubits is `ibmq_melbourne` system. Being just QV8, it doesn't give such a good result when I try to run the even smaller example with (6+1)-qubits.

Anyway, I will update the code to add runs on one of the fake backends in some time.

Thanks again! 😁

**Comment by frankharkins** [comment]
@AbeerVaishnav13 thanks for making these changes, I'll organise a review session ASAP.

**Review by rupeshknn — APPROVED** [review]

**Comment by AbeerVaishnav13** [comment]
> @AbeerVaishnav13 thanks for making these changes, I'll organise a review session ASAP.

Hey @frankharkins, is there any update on the review session?

Also, I was curious about the amount of time that reviewing new chapters and getting them included in the textbook usually takes. I understand that in my case it might take longer as this is my first contribution to the qiskit-textbook and that the quality of the chapters has to be ensured. But could I have just an estimate of the time required for the whole process?

**Comment by frankharkins** [comment]
@AbeerVaishnav13 we will be looking at it tonight :)

**Comment by frankharkins** [comment]
@AbeerVaishnav13 can you either message me on Slack or via email (Francis.Harkins@ibm.com) so we can organise giving feedback please?

**Comment by AbeerVaishnav13** [comment]
Hey @frankharkins , I have made the changes that you suggested and pushed it to the PR. Please review it and let me know if there are any more changes. Thanks!

**Comment by AbeerVaishnav13** [comment]
Hi @frankharkins , is there any update on the status of this PR? Any reviews on my recent commits for the changes that you suggested?

**Review by frankharkins — APPROVED** [review]
Thank you!

**Pull request merged**
