### PR TITLE
translate chapter 4.2.2

### PR DESCRIPTION
**Pull request by daiki0623**
# Changes made

Translated 4.2.2 in Japanese

### CODE REVIEW

**Comment by kifumi** [comment]
@daiki0623 Thank you so much! Can you please add two image files, [circ_eq.png](https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-applications/images/circ_eq.png) and [8x8_2col.png](https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-applications/images/8x8_2col.png) to the folder of ["images"](https://github.com/qiskit-community/qiskit-textbook/tree/main/i18n/locales/ja/ch-applications/images)?

**Comment by kifumi** [comment]
@daiki0623 Thank you so much! Can you please add two image files, [circ_eq.png](https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-applications/images/circ_eq.png) and [8x8_2col.png](https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-applications/images/8x8_2col.png) to the folder of ["images"](https://github.com/qiskit-community/qiskit-textbook/tree/main/i18n/locales/ja/ch-applications/images)?

**Comment by daiki0623** [comment]
oh, missed them. @kifumi added images.

**Review by kifumi — APPROVED** [review]

**Comment by kifumi** [comment]
@daiki0623 Thank you!

**Pull request merged**
