### PR TITLE
[5.5] Fix the extra ')'

### PR DESCRIPTION
**Pull request by devilkiller-ag**
This PR is for solving the issue #1453 
# Changes made
Changed the link to trace on wikipedia in section [Trace and Positivity Conditions](https://qiskit.org/textbook/ch-quantum-hardware/density-matrix.html#Trace-and-Positivity-Conditions-) to eliminate extra ')'. 

# Justification
There is an extra ')' after the link to wikipedia which needs to be eliminated. It was due to '(' and ')' in the link to wikipedia. I encoded them with '%28' for '(' and '%29' for '('.

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
I have changed only one line. I don't know why it's showing that I have deleted 22032 lines.

**Comment by frankharkins** [comment]
@devilkiller-ag it's probably because you've re-run the notebook which has replaced all the images, it's a common problem when working with jupyter notebooks on github. Since your change is small, it's probably easiest to reset the notebook to its original state and make the change again.

1. Check out your main branch and pull in any new changes:
   ```
   git checkout main
   git pull https://github.com/qiskit-community/qiskit-textbook.git main
   ```
2. Make a fresh branch
   ```
   git checkout -b fix-1453
   ```
3. Then make the fix in the notebook
   ```
   jupyter notebook
   ```
   (but don't run any cells)
4. Commit the changes and push
   ```
   git add content/ch-quantum-hardware/density-matrix.ipynb
   git commit -m "Fix issue #1453"
   git push https://github.com/devilkiller-ag/qiskit-textbook.git fix-1453
   ```
5. Go to GitHub and make another PR

Sorry this hasn't been straightforward, I'm working on improving the contributor experience in the new textbook. One of the improvements is to compress images to a single line, which means we can handle cases like this more easily.

**Comment by devilkiller-ag** [comment]
Thanks @frankharkins I will rectify the issue soon.

**Comment by devilkiller-ag** [comment]
Hey @frankharkins I carefully followed all the steps but it's resulting the same condition as before.

**Comment by devilkiller-ag** [comment]
Hey, @frankharkins I have successfully done it. The problem was due to opening it in vs code. It's better to do these changes on a normal browser jupyter notebook. Thanks for help.

**Pull request closed without merging**
