### PR TITLE
Adding a chapter Setting Up the Environment in Prerequisites

### LINKED ISSUE #561: Environment Setup Guide Needed
## Describe the Issue

Users have environments setup differently which can cause confusion when results differ to those seen in the textbook. Many users are also confused that the `qiskit_textbook` package does not come built-in with Qiskit.

## Expected Solution

We need a short explanation in the textbook prerequisites explaining:

- How to install the qiskit_textbook package ([see the Readme](https://github.com/qiskit-community/qiskit-textbook#installing-the-qiskit_textbook-package))
- How to set default drawer to MatPlotLib ([see here](https://qiskit.org/documentation/getting_started.html#step-4-visualize-the-circuit))
- Maybe explain how to set default draw type to svg which is preferred for the website (need to make [this modification to `ipython_kernel_config.py`](https://github.com/qiskit-community/qiskit-textbook/blob/62ce988152405acfbe4339ca8b62f09453041a7b/.ipython/profile_default/ipython_kernel_config.py#L1))
- Can also explain why we display the Qiskit version at the bottom of the page (to help with reproducing code - see #482)

### PR DESCRIPTION
**Pull request by rochisha0**
## Description of Issue (if Applicable)

Fixes #561 

## How Was This Tested?

Please provide any screenshots if applicable.

## 

 Steps

- [x] How to install the qiskit_textbook package (see the Readme)
- [x]  How to set default drawer to MatPlotLib (see here)
- [x] Maybe explain how to set default draw type to svg which is preferred for the website (need to make this modification to ipython_kernel_config.py)
- [x] Can also explain why we display the Qiskit version at the bottom of the page (to help with reproducing code - see #482)

### CODE REVIEW

**Comment by frankharkins** [comment]
@rochisha0 this is great, thank you! Did you decide not to include step 3? If so I will approve and we can merge, otherwise I will wait.

**Comment by rochisha0** [comment]
@frankharkins I don't understand what is to be done in step 3. If you could explain that I'll add that too and then we can merge

**Comment by frankharkins** [comment]
To set the default image format to `svg` the user can add this line:

```c.InlineBackend.figure_format = 'svg'```

to their `ipython_kernel_config.py` file (usually found in `~/.ipython/profile_default`). It should be emphasised this is optional, and is included to help reproduce the prerendered output on the website.

**Comment by rochisha0** [comment]
@frankharkins I've made the necessary changes please, review.

**Pull request merged**
