### PR TITLE
0.1 - Added Conda recommendation; called out auto-install of Qiskit

### PR DESCRIPTION
**Pull request by krsnaa**
# Changes made
Added best practice recommendation of setting up the qiskit_textbook package in a virtual environment.
Called out the fact that the qiskit_textbook package installs the base Qiskit package as a dependency automatically.

# Justification
Never a good idea to install python packages in the global namespace.
It is confusing when following this documentation for the first time whether we need to install Qiskit separately before installing qiskit_textbook.

### CODE REVIEW

**Comment by jwoehr** [comment]
IMHO Conda is not a bad recommendation for Windows "users-only" but anyone who wants to hack on Qiskit source code should avoid it.

**Comment by frankharkins** [comment]
@krsnaa can you sign the CLA please so I can merge? [There's a link in this comment.](https://github.com/qiskit-community/qiskit-textbook/pull/668#issuecomment-673147484)

**Comment by frankharkins** [comment]
@krsnaa friendly ping to ask you to sign the CLA. Unfortunately I cannot merge until you have done so.

**Comment by frankharkins** [comment]
I'm going to close this as I can't merge until the CLA is signed. @krsnaa please feel free to re-open if you sign.

**Pull request closed without merging**
