### PR TITLE
Fix issue 1038

### PR DESCRIPTION
**Pull request by rafal-pracht**
# Changes made
I replace the "result = job.result().get_counts(self._circuit)" by "result = job.result().get_counts()" in definition of QuantumCircuit.
Justification

# Justification
Regarding to issue  #1038 the new version is incompatible with experiments in textbook.

### CODE REVIEW

**Comment by rafal-pracht** [comment]
This is the same fix as in https://github.com/qiskit-community/qiskit-textbook/pull/1072

**Comment by rafal-pracht** [comment]
@jwoehr, please go to the "Checks" tab and see on "Build and Deploy" where you can see the strange error:

Johny, please go to the "Checks" tab and see on "Build and Deploy" where you can see the strange error:

   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 47, in block 'outputs'
    {%- block output scoped -%}
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_book/page/templates/html.tpl", line 12, in block 'output'
    <div class="jb_output_wrapper{%- if 'interactive' in cell.metadata.tags %} output_widget_view {% endif %} }}">
jinja2.exceptions.UndefinedError: 'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'
make: *** [Makefile:22: book] Error 1
Error: Process completed with exit code 2.

image

**Review by frankharkins — APPROVED** [review]
Thank you!

**Comment by frankharkins** [comment]
I don't understand why this is failing, let me investigate.

**Comment by vabarbosa** [comment]
thanks... the build error should be resolved now

**Pull request merged**
