### PR TITLE
5.1 Fixed issue769 by changing the number of shots

### PR DESCRIPTION
**Pull request by tgag17**
# Changes made

Fixes issue #769 
Changed the number of shots from default(1024) to 10000
# Justification

The text mentioned that the number of shots for a particular case are less than 100 making it less than 1% which is true for 10000 shots. Also the cases mentioned in the text were only generated with shots greater than 1024

### CODE REVIEW

**Comment by frankharkins** [comment]
@tgag17 @YumaNK From what I understand of the issue (#769): The problem is that 100 is not approximately 1% of 1024, so the phrase:
> much less than less than 100 samples come out with a majority of 1s. When using this circuit to encode a 0, this means that P < 1%

is not correct? 

You seem to have changed the number of shots to match this statement, but you have not changed the line:

> We'll repeat the process shots=1024 times to see how likely different results are.

So either this needs changing too, or we keep the original code and simply change the line to read:

> much less than less than **10** samples come out with a majority of 1s. When using this circuit to encode a 0, this means that P < 1%

Please let me know if I have misunderstood this.

**Comment by tgag17** [comment]
@frankharkins Sorry, I think I missed the line in the context. If we keep the original code then the cases with majority of 1s are not generated at all. So what do you recommend should be done

**Comment by frankharkins** [comment]
That's ok right? As 0 << 10

**Comment by tgag17** [comment]
Oh ok. I was also confused as to what changes should be made and thus discussed it before editing. It would be better to just change the 100 to 10 then.

**Comment by tgag17** [comment]
Should this PR be closed and another one be opened?

**Comment by frankharkins** [comment]
You can make the changes in this PR, or open another if it's easier for you.

**Pull request closed without merging**
