### PR TITLE
Adds a Notebook on Variational Thermofield Double State Generation (Work in Progress)

### PR DESCRIPTION
**Pull request by Lucaman99**
This pull request adds a new Notebook to the "Recent Papers" section of the Qiskit textbook, on the topic of generating TFD states with variational quantum circuits. This Notebook is based on the research outlined in https://arxiv.org/abs/1906.02699.

This is the first draft of the Notebook, there are still a few things that I am slightly unsure of, relating to the mathematical derivations at the beginning (as the paper omits quite a bit when it comes to formally laying out all of the math, so I had to fill in the gaps myself), so I was hoping that I might be able to get a second opinion!

### CODE REVIEW

**Comment by Lucaman99** [comment]
Hey @aasfaw @frankharkins! Is there a new process for code review, for textbook submissions?

**Comment by frankharkins** [comment]
Are the changes to VQLS intentional? It's hard to see from the diff.

**Comment by Lucaman99** [comment]
@frankharkins I think I may have re-run one of the cells/fixed a couple of typos. No major changes at all.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this pull request as this repository is no longer used and is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this pull request there if it's still relevant.

**Pull request closed without merging**
