### PR TITLE
Removed redundancy

### PR DESCRIPTION
**Pull request by paniash**
## Description of Issue (if Applicable)
Removed redundancy in code.

## What Changes Were Made?
Changed `display(qc.draw())` to `qc.draw()` wherever applicable.

## How Was This Tested?
IPython shell.

### CODE REVIEW

**Comment by frankharkins** [comment]
@paniash this doesn't work in Jupyter Notebooks (the recommended course of reading the textbook). Since the notebook only displays `qc.draw()` automatically when it is the last line in a cell. Maybe we could add a comment explaining this for other users instead of removing them?

**Comment by paniash** [comment]
@frankharkins Please correct me if I'm wrong but doesn't `%matplotlib inline` enable `qc.draw()` to work on Jupyter Notebooks?
If not, then please allow me to follow your suggestions and make another pull request.

**Comment by paniash** [comment]
I tried the code block in Jupyter Notebook and it seems to work fine on my system.

**Comment by frankharkins** [comment]
This is what I get (even when including `%matplotlib inline`). The circuit does not draw without `display()`. 

Screenshot 2020-06-25 at 15 17 38

Do you know if there's a way to fix this on my device? If so we should add it to the readme.

**Comment by paniash** [comment]
I see what the problem was. When running just `qc.draw()`, I get a separate window displaying the circuit (it doesn't draw in the notebook itself). Only when running `display(qc.draw())`, do i get a separate window as well as the circuit on the notebook.

I think it will be better to include this as a comment. Also, shouldn't this change be propagated to the previous chapters as well since those contain only `qc.draw()` instead of `display(qc.draw())`. I had been using IPython all this while and as unaware of this difference.

**Comment by nonhermitian** [comment]
The circuit will not draw because only the last fig is captured. Matplotlib inline is actually legacy code. It is done by default these days. The display is forcing the output. One could also print the circuit, although may not be ideal.

**Pull request closed without merging**
