### PR TITLE
[5.5] Fix the extra ')'

### PR DESCRIPTION
**Pull request by devilkiller-ag**
# Changes made
Changed the link to trace on wikipedia in section [Trace and Positivity Conditions](https://qiskit.org/textbook/ch-quantum-hardware/density-matrix.html#Trace-and-Positivity-Conditions-) to eliminate extra ')'.

# Justification
There is an extra ')' after the link to wikipedia which needs to be eliminated. It was due to '(' and ')' in the link to wikipedia. I encoded them with '%28' for '(' and '%29' for '('.

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
Can someone please review my PR? @nkanazawa1989

**Comment by frankharkins** [comment]
@devilkiller-ag sorry, I can't see any changes, looks like something strange happened to your fork 😕

**Comment by devilkiller-ag** [comment]
Kindly review the changes now. Sorry for the inconvenience before.

**Comment by frankharkins** [comment]
Hi, sorry but you've now removed 22,000 lines and the diff is too large to show on GitHub; can you reset the notebook and make the change again?

**Comment by devilkiller-ag** [comment]
Sure @frankharkins

**Comment by devilkiller-ag** [comment]
I am closing this PR and making a new [PR](https://github.com/qiskit-community/qiskit-textbook/pull/1498) for this. Kindly check that PR. Sorry for the inconveniences.

**Pull request closed without merging**
