### PR TITLE
trying to fix #521

### LINKED ISSUE #521: 4.1.5 images being overlapped
## Describe the Issue
https://qiskit.org/textbook/ch-machine-learning/machine-learning-qiskit-pytorch.html
images here are being overlapped by the column on the right.

## Expected Solution
image width adjust to the available center column space

## Anything else we should know?
I'm very much temped to suggest trimming the white space on the left side of [this image](https://github.com/qiskit-community/qiskit-textbook/blob/master/content/ch-machine-learning/neuralnetworkQC.png) too.

### PR DESCRIPTION
**Pull request by omarcostahamido**
I'm thinking this may be able to fix #521

## Description of Issue (if Applicable)

Fixes #your_issue_number_here

## How Was This Tested?

Please provide any screenshots if applicable.

### CODE REVIEW

**Comment by frankharkins** [comment]
Interesting, I had not caught this. I didn't realise those images had the width specified in the tags. Can you try removing the width from those tags completely and see if that also fixes it?

e.g. 

``

to:

``

**Comment by omarcostahamido** [comment]
hi @frankharkins 
Sorry about the delay.
I've made the changes.
Hopefully it will work well.

Thanks,
OCH

**Comment by omarcostahamido** [comment]
Perfect!

**Comment by frankharkins** [comment]
@omarcostahamido the live site should be updated now, can you please check it works correctly?

**Comment by omarcostahamido** [comment]
@frankharkins super! it is working nicely now.
Thank you.

OCH

**Pull request merged**
