### PR TITLE
Fixed a typo [6.3]

### LINKED ISSUE #1005: [6.3] A mixup of kinetic and potential energy in the LC circuit?
**Describe the issue**
On page: content/ch-quantum-hardware/transmon-physics.ipynb

In the sentence "The Hamiltonian is the sum of the kinetic energy (represented by charge variable Q) and potential energy (represented by flux variable Φ)," I believe it should be the other way around.

**Describe what you expect to see**
"The Hamiltonian is the sum of the potential energy (represented by charge variable Q) and kinetic energy (represented by flux variable Φ), "

This fits better with my dusty old electrical engineer intuition, and seems to be how others have described it elsewhere.

### PR DESCRIPTION
**Pull request by divshacker**
# Changes made

fixes #1005 
# Justification

All details of the typo can be found in above linked issue

### CODE REVIEW

**Comment by divshacker** [comment]
@frankharkins  @nonhermitian @SooluThomas  Check this PR.

**Review by nbronn — COMMENTED** [review]
So this can work either way, it depends on what you take as the definition, and I prefer thinking of the energy potential profile in terms of phase/flux. If you consider the "Branch-Flux Method for Linear Circuits," you'll see this should be consistent in the Hamiltonian definition there.

**Comment by divshacker** [comment]
> So this can work either way, it depends on what you take as the definition, and I prefer thinking of the energy potential profile in terms of phase/flux. If you consider the "Branch-Flux Method for Linear Circuits," you'll see this should be consistent in the Hamiltonian definition there.

If that's the case then there is no point in opening this PR. May I close this PR then? @nbronn

**Comment by nbronn** [comment]
> > So this can work either way, it depends on what you take as the definition, and I prefer thinking of the energy potential profile in terms of phase/flux. If you consider the "Branch-Flux Method for Linear Circuits," you'll see this should be consistent in the Hamiltonian definition there.
> 
> If that's the case then there is no point in opening this PR. May I close this PR then? @nbronn

Please do!

**Pull request closed without merging**
