### PR TITLE
Update hhl_tutorial.ipynb(version table)

### PR DESCRIPTION
**Pull request by rajat709**
# Changes made

# Justification

### CODE REVIEW

**Review by dhruvbhq — COMMENTED** [review]
Hi @rajat709 , thanks for contributing!

It might be a good idea to fill out the PR template/description, so that your contribution gets the attention that it correctly deserves!

It appears the PRs #1242 to #1249 address very similar changes (by changing version information to version table). Did you consider the possibility of implementing these changes in a single PR (or maybe a draft PR first, with multiple commits)? I think that it should have indeed been possible, and would have been neater. Maybe @frankharkins has some suggestion?

**Comment by rajat709** [comment]
but, how can i merge all PRs in single PR??

**Comment by frankharkins** [comment]
@rajat709 thanks again. For now this is fine as separate PRs, but in the future, since the changes are all very similar, it's better to make it a single PR. You can do this by either merging the different branches into a single branch before making the PR, or by working off the same branch.

More important is the problem about the version table matching the code that was used to produce the outputs. This is the same problem as in the Hamiltonian tomography PR ([see here](https://github.com/qiskit-community/qiskit-textbook/pull/1249#issuecomment-891127110)).

**Comment by frankharkins** [comment]
Closing RE [this comment](https://github.com/qiskit-community/qiskit-textbook/pull/1249#issuecomment-891127110). Please open another PR if you still want to work on this. Thanks.

**Pull request closed without merging**
