### PR TITLE
Changed tensor to kronecker

### PR DESCRIPTION
**Pull request by martinchristensen**
kronecker product is more precise than tensor product.

# Changes made

# Justification

### CODE REVIEW

**Review by frankharkins — APPROVED** [review]
Awesome thanks!

**Comment by frankharkins** [comment]
@martinchristensen turns out I was too hasty to merge this. Can you please sign the CLA? Otherwise I will need to revert the commit.

**Comment by martinchristensen** [comment]
@frankharkins I just signed it 👍

**Comment by frankharkins** [comment]
Thank you!

**Pull request merged**
